### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lonerz**

### CODE REVIEW

**Comment by lonerz** [comment]
#3

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an pull request with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an issue with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an issue with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an issue with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-api, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an issue with the "area: analytics", "area: api", "area: authentication", "area: bots" labels, so you may want to check it out!

**Pull request closed without merging**
