### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lonerz**

### CODE REVIEW

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-api members, this pull request was labeled with the **area: api** label, so you may want to check it out!

**Comment by lonerz** [comment]
#6

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-api members, this pull request references an pull request with the "area: api" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-api members, this pull request references an pull request with the "area: api" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-api members, this pull request references an pull request with the "area: api" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-api members, this pull request references an pull request with the "area: api" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-api members, this pull request references an issue with the "area: api" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics members, this pull request was labeled with the **area: analytics** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
testing

**Comment by zulipbot-test** [comment]
Hello @[author], it seems like you have referenced an pull request in your
comments, but have not referenced that issue in your commit message(s).
When you reference the issue in the commit message, it closes the issue
once your commit is merged. Use `git commit --amend` to amend your
commit message with "Fixes #[issue number]".

**Comment by zulipbot-test** [comment]
Hello @[author], it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with "Fixes #[issue number]".

**Comment by zulipbot-test** [comment]
Hello @[author], it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @undefined, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @undefined, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by lonerz** [comment]
test

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an pull request in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an issue in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an issue in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue for Zulip maintainers once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-analytics, @zulipbot-testing/server-authentication, @zulipbot-testing/server-bots members, this pull request references an issue with the "area: analytics", "area: authentication", "area: bots" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @lonerz, it seems like you have referenced an issue in your comments, but have not referenced that issue in your commit message(s). When you reference the issue in the commit message, it closes the issue for Zulip maintainers once your commit is merged.

Use `git commit --amend` to amend your commit message with `"Fixes #[issue number]"`.

An example of a correctly-formatted commit:
```
commit 877c29919d88fae3a995389c3f80a3be6a4dc8f4
Author: Joshua Pan <joshuapan8@gmail.com>
Date:   Sat Mar 18 13:15:26 2017 -0700

    Check PR commits reference when issue referenced.

    Fixes #51.

**Pull request closed without merging**
